# Generated by Django 4.2.9 on 2026-01-16 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('storage_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('chunks_uploaded', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'indexes': [models.Index(fields=['owner', 'status'], name='files_owner_i_c24b2d_idx'), models.Index(fields=['checksum'], name='files_checksu_50732f_idx')],
            },
        ),
    ]
