# Generated by Django 4.2.9 on 2026-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
